# ── Vogue Events Infrastructure Definition ──────────────
# This file defines all infrastructure for Vogue Events
# as code — reproducible, version-controlled, auditable.

terraform {
  required_version = ">= 1.0"

  required_providers {
    # Vercel provider for deployment management
    vercel = {
      source  = "vercel/vercel"
      version = "~> 1.0"
    }

    # Local provider for file generation
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }

    # Random provider for generating secure tokens
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

# ── Provider Configuration ───────────────────────────────

provider "vercel" {
  api_token = var.vercel_api_token
  team      = var.vercel_team_id != "" ? var.vercel_team_id : null
}

# ── Random secret for internal use ──────────────────────

resource "random_password" "session_secret" {
  length  = 64
  special = true
}

# ── Vercel Project ───────────────────────────────────────

resource "vercel_project" "vogue_events" {
  name      = var.project_name
  framework = "nextjs"

  # Auto-deploy on push to main branch
  git_repository = {
    type              = "github"
    repo              = "favour-tamfu/Vogue"
    production_branch = "main"
  }

  # Build configuration
  build_command    = "npm run build"
  output_directory = ".next"
  install_command  = "npm install"

  # Enable server-side rendering
  serverless_function_region = "iad1"
}

# ── Environment Variables ────────────────────────────────
# Injected securely at build and runtime — never in code

resource "vercel_project_environment_variable" "supabase_url" {
  project_id = vercel_project.vogue_events.id
  key        = "NEXT_PUBLIC_SUPABASE_URL"
  value      = var.supabase_url
  target     = ["production", "preview", "development"]
}

resource "vercel_project_environment_variable" "supabase_anon_key" {
  project_id = vercel_project.vogue_events.id
  key        = "NEXT_PUBLIC_SUPABASE_ANON_KEY"
  value      = var.supabase_anon_key
  target     = ["production", "preview", "development"]
}

resource "vercel_project_environment_variable" "supabase_service_role" {
  project_id = vercel_project.vogue_events.id
  key        = "SUPABASE_SERVICE_ROLE_KEY"
  value      = var.supabase_service_role_key
  target     = ["production"]
}

resource "vercel_project_environment_variable" "admin_password" {
  project_id = vercel_project.vogue_events.id
  key        = "ADMIN_PASSWORD"
  value      = var.admin_password
  target     = ["production"]
}

resource "vercel_project_environment_variable" "session_secret" {
  project_id = vercel_project.vogue_events.id
  key        = "SESSION_SECRET"
  value      = random_password.session_secret.result
  target     = ["production"]
}

# ── Generate local .env file for development ─────────────

resource "local_file" "env_example" {
  filename = "${path.module}/../.env.example"
  content  = <<-EOT
    # ── Generated by Terraform ──────────────────────────
    # Copy this to .env.local and fill in your values
    # DO NOT commit .env.local to version control

    # Supabase
    NEXT_PUBLIC_SUPABASE_URL=your_supabase_project_url
    NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
    SUPABASE_SERVICE_ROLE_KEY=your_service_role_key

    # Admin Panel
    ADMIN_PASSWORD=your_secure_admin_password

    # Auto-generated session secret
    SESSION_SECRET=your_session_secret
  EOT
}
